buildscript {
    ext {
        androidx_appcompat_version = "1.7.1"
        androidx_exifinterface_version = "1.4.1"
        androidx_transition_version = "1.6.0"
        constraintlayout_version = "2.2.1"
        agp_version = '8.11.1'
        kotlin_version = '2.2.0'
    }

    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

def isReleaseBuild() {
    return version.contains("SNAPSHOT") == false
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
